"""initial spine: signal through outcome

Revision ID: 0e7a61c13abe
Revises: 
Create Date: 2026-09-17 21:54:41.541696

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e7a61c13abe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_fingerprint', 'incident', ['fingerprint'], unique=False)
    op.create_table('signal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_source_kind_observed_at', 'signal', ['source', 'kind', 'observed_at'], unique=False)
    op.create_index('ix_signal_target', 'signal', ['target'], unique=False)
    op.create_table('incident_signal',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'signal_id')
    )
    op.create_table('outcome',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('mttr_sec', sa.Integer(), nullable=True),
    sa.Column('regression', sa.Boolean(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_incident_id'), 'outcome', ['incident_id'], unique=False)
    op.create_table('proposal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_proposal_confidence_range'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_incident_id'), 'proposal', ['incident_id'], unique=False)
    op.create_table('action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('blast_radius', sa.Enum('pod', 'deployment', 'namespace', 'node', 'account', name='blast_radius'), nullable=False),
    sa.Column('policy_class', sa.Enum('auto', 'ask', 'never', name='policy_class'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_proposal_id'), 'action', ['proposal_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('approved', 'denied', 'auto_approved', name='verdict'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_decision_action_id')
    )
    op.create_table('execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='execution_status'), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_execution_action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution')
    op.drop_table('decision')
    op.drop_index(op.f('ix_action_proposal_id'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_proposal_incident_id'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_outcome_incident_id'), table_name='outcome')
    op.drop_table('outcome')
    op.drop_table('incident_signal')
    op.drop_index('ix_signal_target', table_name='signal')
    op.drop_index('ix_signal_source_kind_observed_at', table_name='signal')
    op.drop_table('signal')
    op.drop_index('ix_incident_fingerprint', table_name='incident')
    op.drop_table('incident')
    # ### end Alembic commands ###

    # Autogenerate drops the tables but not the PostgreSQL ENUM types backing
    # them — a known Alembic gap. Without this, downgrade-then-upgrade fails
    # with "type already exists". Verified by actually round-tripping this
    # migration against a live Postgres, not assumed.
    for enum_name in (
        "severity",
        "risk_level",
        "blast_radius",
        "policy_class",
        "verdict",
        "execution_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
