#!/usr/bin/env python3
"""Generate the Kaval progress dashboard.

Reads the repository and renders docs/dashboard.html. Nothing here records
status: ROADMAP.md is the single source of truth, and this only reflects it.
That is deliberate -- a dashboard holding its own copy of "what's done" drifts
within two sessions and then actively misleads.

    python scripts/dashboard.py
    make dashboard

Python 3.11 stdlib only. No pip install.
"""

from __future__ import annotations

import html
import json
import re
import subprocess
import tomllib
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "dashboard.html"


# ─────────────────────────────────────────────────────────────
# Parsing
# ─────────────────────────────────────────────────────────────

STATUS_LABEL = {" ": "not started", "~": "in progress", "x": "done"}


@dataclass
class Phase:
    num: int
    title: str
    weeks: str
    marker: str
    tasks: list[tuple[bool, str]] = field(default_factory=list)
    exit_gate: str = ""

    @property
    def done(self) -> int:
        return sum(1 for ok, _ in self.tasks if ok)

    @property
    def total(self) -> int:
        return len(self.tasks)

    @property
    def pct(self) -> int:
        return round(100 * self.done / self.total) if self.total else 0

    @property
    def state(self) -> str:
        return STATUS_LABEL.get(self.marker, "not started")


def read_roadmap(path: Path) -> list[Phase]:
    head = re.compile(r"^## Phase (\d+) — (.+?) · weeks? (.+?) · `\[(.)\]`")
    task = re.compile(r"^- \[([ x])\] (.+)")
    gate = re.compile(r"^\*\*Exit gate:\*\* (.+)")

    phases: list[Phase] = []
    current: Phase | None = None

    for line in path.read_text(encoding="utf-8").splitlines():
        if m := head.match(line):
            current = Phase(int(m[1]), m[2].strip(), m[3].strip(), m[4])
            phases.append(current)
        elif current is None:
            continue
        elif m := task.match(line):
            current.tasks.append((m[1] == "x", m[2].strip()))
        elif m := gate.match(line):
            current.exit_gate = m[1].strip()

    return phases


def read_adrs(d: Path) -> list[dict]:
    num_re = re.compile(r"^# ADR-(\d+) — (.+)")
    st_re = re.compile(r"^- \*\*Status:\*\* (.+)")

    out = []
    for f in sorted(d.glob("[0-9]*.md")):
        text = f.read_text(encoding="utf-8")
        n = num_re.search(text, re.M) or re.search(num_re.pattern, text, re.M)
        s = re.search(st_re.pattern, text, re.M)
        if not n:
            continue
        status = s[1].strip() if s else "unknown"
        out.append({
            "id": f"ADR-{n[1]}",
            "title": n[2].strip(),
            "status": status,
            "open": status.lower().startswith("proposed"),
            "file": f.name,
        })
    return out


def read_labs(d: Path) -> list[dict]:
    title_re = re.compile(r"^# Lab (\d+) — (.+)", re.M)
    meta_re = re.compile(r"^\*\*Phase:\*\* (\S+).*?\*\*Cost:\*\* (\S+)", re.M)

    out = []
    for f in sorted(d.glob("lab-*.md")):
        text = f.read_text(encoding="utf-8")
        t = title_re.search(text)
        if not t:
            continue
        meta = meta_re.search(text)
        done = len(re.findall(r"^- \[x\]", text, re.M))
        total = done + len(re.findall(r"^- \[ \]", text, re.M))
        out.append({
            "id": f"Lab {t[1]}",
            "title": t[2].strip(),
            "phase": meta[1] if meta else "?",
            "cost": meta[2] if meta else "?",
            "done": done,
            "total": total,
            "file": f.name,
        })
    return out


def read_journal(d: Path) -> tuple[list[dict], list[str]]:
    """Return (sessions newest-first, open threads from the newest entry)."""
    sessions = []
    for f in sorted(d.glob("[0-9]*.md"), reverse=True):
        text = f.read_text(encoding="utf-8")
        phase = re.search(r"^\*\*Phase:\*\* (.+)", text, re.M)
        done = len(re.findall(r"^- ", text, re.M))
        sessions.append({
            "date": f.stem,
            "phase": phase[1].strip() if phase else "",
            "lines": done,
            "text": text,
            "file": f.name,
        })

    threads: list[str] = []
    if sessions:
        block = re.search(
            r"^## Open threads\s*\n(.*?)(?=\n## |\Z)", sessions[0]["text"], re.M | re.S
        )
        if block:
            # Bullets may wrap across lines; join continuations back on.
            for raw in re.split(r"\n(?=- )", block[1].strip()):
                item = " ".join(raw.strip().lstrip("- ").split())
                if item:
                    threads.append(item)
    return sessions, threads


def read_releases(d: Path) -> list[dict]:
    """Change records generated by promote.yml. Empty until the first release,
    which is honest -- the panel says so rather than inventing figures."""
    if not d.is_dir():
        return []
    out = []
    # Date-prefixed files only. README.md documents the format and contains a
    # worked example, which would otherwise be parsed as a real release.
    for f in sorted(d.glob("[0-9]*.md"), reverse=True):
        text = f.read_text(encoding="utf-8")
        t = re.search(r"^# Release (v[\d.]+) — (\d{4}-\d{2}-\d{2})", text, re.M)
        if not t:
            continue

        def field(name: str) -> str:
            m = re.search(rf"^- \*\*{name}:\*\* *(.+)", text, re.M)
            return m[1].strip() if m else ""

        rolled = field("Rolled back").lower().startswith(("yes", "true"))
        out.append({
            "version": t[1],
            "date": t[2],
            "env": field("Environment") or "prod",
            "approver": field("Approved by"),
            "digest": field("Digest")[:14],
            "lead_time": field("Lead time"),
            "restore": field("Time to restore"),
            "rolled_back": rolled,
        })
    return out


def dora(releases: list[dict], started: date, today: date) -> dict:
    """The four DORA metrics, derived from the change records. Speed and
    stability, two pairs -- reporting only one pair is how teams justify
    shipping recklessly, or never shipping at all."""
    prod = [r for r in releases if r["env"] == "prod"]
    if not prod:
        return {}
    weeks = max(1.0, (today - date.fromisoformat(prod[-1]["date"])).days / 7)
    failed = sum(1 for r in prod if r["rolled_back"])
    restores = [r["restore"] for r in prod if r["restore"]]
    return {
        "frequency": f"{len(prod) / weeks:.1f}/week",
        "lead_time": prod[0]["lead_time"] or "—",
        "change_failure": f"{failed} of {len(prod)}",
        "restore": restores[0] if restores else "not yet measured",
    }


def git_log(n: int = 8) -> list[dict]:
    try:
        raw = subprocess.run(
            ["git", "log", f"-{n}", "--date=short", "--format=%h\x1f%ad\x1f%s"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    out = []
    for line in raw.strip().splitlines():
        if line.count("\x1f") == 2:
            h, d, s = line.split("\x1f")
            out.append({"hash": h, "date": d, "subject": s})
    return out


# ─────────────────────────────────────────────────────────────
# Markdown
# ─────────────────────────────────────────────────────────────
#
# Hand-rolled against stdlib only. The input is our own documents, not
# arbitrary Markdown, so a focused converter is enough -- and it keeps the
# zero-dependency property that lets this run on a machine with no pip.
# Supports: headings, paragraphs, lists, fenced code, tables, blockquotes,
# horizontal rules, and inline code/bold/italic/links.

def _inline(s: str) -> str:
    s = html.escape(s, quote=False)
    # Code first: its contents must not be touched by the other rules.
    holds: list[str] = []

    def stash(m: re.Match) -> str:
        holds.append(f"<code>{m[1]}</code>")
        return f"\x00{len(holds) - 1}\x00"

    s = re.sub(r"`([^`]+)`", stash, s)

    def link(m: re.Match) -> str:
        text, href = m[1], m[2]
        # Repo-relative links are dead once this is published as a single page.
        # Keep the reference visible as a path instead of a broken anchor.
        if not re.match(r"^(https?://|#|mailto:)", href):
            return f"<code>{text}</code>"
        return f'<a href="{href}">{text}</a>'

    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![*\w])\*([^*\n]+)\*(?!\w)", r"<em>\1</em>", s)
    return re.sub(r"\x00(\d+)\x00", lambda m: holds[int(m[1])], s)


def _cells(row: str) -> list[str]:
    return [c.strip() for c in row.strip().strip("|").split("|")]


def markdown_to_html(md: str) -> str:
    out: list[str] = []
    lines = md.split("\n")
    i, n = 0, len(lines)

    while i < n:
        line = lines[i]

        # fenced code
        if line.startswith("```"):
            i += 1
            body = []
            while i < n and not lines[i].startswith("```"):
                body.append(lines[i])
                i += 1
            i += 1
            out.append(f"<pre><code>{html.escape(chr(10).join(body))}</code></pre>")
            continue

        # table -- header, separator, then rows
        if line.startswith("|") and i + 1 < n and re.match(r"^\|[\s:|-]+\|$", lines[i + 1]):
            head = _cells(line)
            i += 2
            rows = []
            while i < n and lines[i].startswith("|"):
                rows.append(_cells(lines[i]))
                i += 1
            th = "".join(f"<th>{_inline(c)}</th>" for c in head)
            tb = "".join(
                "<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in r) + "</tr>" for r in rows
            )
            out.append(f'<div class="tw"><table><thead><tr>{th}</tr></thead><tbody>{tb}</tbody></table></div>')
            continue

        # heading
        if m := re.match(r"^(#{1,4}) +(.+)", line):
            lvl = len(m[1])
            out.append(f"<h{lvl}>{_inline(m[2])}</h{lvl}>")
            i += 1
            continue

        # horizontal rule
        if re.match(r"^-{3,}$", line.strip()):
            out.append("<hr>")
            i += 1
            continue

        # blockquote
        if line.startswith(">"):
            body = []
            while i < n and lines[i].startswith(">"):
                body.append(lines[i].lstrip("> ").rstrip())
                i += 1
            out.append("<blockquote>" + "<br>".join(_inline(b) for b in body if b) + "</blockquote>")
            continue

        # list -- ordered or unordered, one level
        if re.match(r"^(\d+\.|[-*]) +", line):
            ordered = bool(re.match(r"^\d+\.", line))
            items: list[str] = []
            while i < n and re.match(r"^(\d+\.|[-*]) +", lines[i]):
                items.append(re.sub(r"^(\d+\.|[-*]) +", "", lines[i]))
                i += 1
                # fold wrapped continuation lines into the current item
                while i < n and lines[i].strip() and not re.match(r"^(\d+\.|[-*]|#|\||>|```)", lines[i]):
                    items[-1] += " " + lines[i].strip()
                    i += 1
            tag = "ol" if ordered else "ul"
            body = "".join(f"<li>{_inline(x)}</li>" for x in items)
            out.append(f"<{tag}>{body}</{tag}>")
            continue

        # blank
        if not line.strip():
            i += 1
            continue

        # paragraph
        para = [line]
        i += 1
        while i < n and lines[i].strip() and not re.match(r"^(#{1,4} |[-*] |\d+\.|\||>|```|-{3,}$)", lines[i]):
            para.append(lines[i])
            i += 1
        out.append(f"<p>{_inline(' '.join(x.strip() for x in para))}</p>")

    return "\n".join(out)


@dataclass
class Learn:
    num: int | None          # None for a cross-cutting page
    key: str                 # hash route: "phase-3" or "release-engineering"
    slug: str
    title: str
    written_from: str
    body: str
    terms: int

    @property
    def eyebrow(self) -> str:
        return f"Phase {self.num}" if self.num is not None else "Cross-cutting"


def read_learn(d: Path) -> list[Learn]:
    """Numbered phase pages, plus any cross-cutting page — release-engineering.md
    spans phases 1, 3 and 4, so it has no number and sorts last."""
    if not d.is_dir():
        return []
    out = []
    for f in sorted(d.glob("*.md")):
        text = f.read_text(encoding="utf-8")
        wf = re.search(r"\*\*Written from:\*\* *(\w+)", text)
        # Glossary rows: table lines under the Glossary heading.
        gl = re.search(r"^## Glossary\s*\n(.*?)(?=\n## |\Z)", text, re.M | re.S)
        terms = len(re.findall(r"^\| \*\*", gl[1], re.M)) if gl else 0

        phased = re.search(r"^# Phase (\d+) — (.+)", text, re.M)
        if phased:
            num, key, title = int(phased[1]), f"phase-{phased[1]}", phased[2].strip()
        else:
            plain = re.search(r"^# (.+)", text, re.M)
            if not plain:
                continue
            num, key, title = None, f.stem, plain[1].strip()

        out.append(Learn(
            num=num, key=key, slug=f.stem, title=title,
            written_from=(wf[1] if wf else "theory"),
            body=markdown_to_html(text),
            terms=terms,
        ))
    # Numbered pages in order, cross-cutting pages after them.
    return sorted(out, key=lambda x: (x.num is None, x.num if x.num is not None else 0, x.slug))


# ─────────────────────────────────────────────────────────────
# Architecture diagrams
# ─────────────────────────────────────────────────────────────
#
# Nodes and edges are declared in architecture.toml; each node names the
# phase it arrives in, and its drawn state is derived from that phase's
# marker in ROADMAP.md. So the diagram fills in as phases complete and
# cannot drift from reality -- the same discipline as the board.

NODE_W, NODE_H = 156, 50
COL_GAP, ROW_GAP = 30, 52
PAD = 16


def _status_for(phase: int | None, phases: list[Phase]) -> str:
    if phase is None:
        return "planned"
    for p in phases:
        if p.num == phase:
            return {"x": "built", "~": "active"}.get(p.marker, "planned")
    return "planned"


def _xy(node: dict) -> tuple[float, float]:
    return (
        PAD + float(node["col"]) * (NODE_W + COL_GAP),
        PAD + float(node["row"]) * (NODE_H + ROW_GAP),
    )


def _edge_path(a: dict, b: dict) -> tuple[str, float, float]:
    """Orthogonal path from node a to node b, plus a label anchor point."""
    ax, ay = _xy(a)
    bx, by = _xy(b)
    acx, bcx = ax + NODE_W / 2, bx + NODE_W / 2

    if abs(float(a["row"]) - float(b["row"])) < 0.01:          # same lane
        if bx > ax:
            x1, x2 = ax + NODE_W, bx
        else:
            x1, x2 = ax, bx + NODE_W
        y = ay + NODE_H / 2
        return f"M {x1} {y} L {x2} {y}", (x1 + x2) / 2, y - 7

    if float(b["row"]) > float(a["row"]):                       # downward
        y1, y2 = ay + NODE_H, by
    else:                                                       # upward
        y1, y2 = ay, by + NODE_H

    mid = (y1 + y2) / 2
    if abs(acx - bcx) < 1:
        return f"M {acx} {y1} L {acx} {y2}", acx, (y1 + y2) / 2
    return (
        f"M {acx} {y1} L {acx} {mid} L {bcx} {mid} L {bcx} {y2}",
        (acx + bcx) / 2,
        mid - 7,
    )


def render_diagram(view: str, nodes: list[dict], edges: list[dict],
                   phases: list[Phase]) -> tuple[str, dict]:
    by_id = {n["id"]: n for n in nodes}
    width = PAD * 2 + max(float(n["col"]) for n in nodes) * (NODE_W + COL_GAP) + NODE_W
    minx = min(float(n["col"]) for n in nodes) * (NODE_W + COL_GAP)
    height = PAD * 2 + max(float(n["row"]) for n in nodes) * (NODE_H + ROW_GAP) + NODE_H

    out = [
        f'<svg class="diagram" viewBox="{minx - PAD} 0 {width - minx + PAD} {height}" '
        f'width="{width - minx + PAD}" height="{height}" '
        f'role="img" aria-label="{e(view)} diagram">',
        '<defs>'
        '<marker id="ah" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" '
        'markerHeight="7" orient="auto-start-reverse">'
        '<path d="M0,0 L8,4 L0,8 z" fill="currentColor"/></marker>'
        '</defs>',
    ]

    for ed in edges:
        a, b = by_id.get(ed["from"]), by_id.get(ed["to"])
        if not a or not b:
            continue
        d, lx, ly = _edge_path(a, b)
        kind = ed.get("kind", "flow")
        state = "built" if (_status_for(a.get("phase"), phases) == "built"
                            and _status_for(b.get("phase"), phases) == "built") else "planned"
        out.append(f'<path class="ed {kind} {state}" d="{d}" marker-end="url(#ah)"/>')
        if ed.get("label"):
            out.append(
                f'<text class="edl {state}" x="{lx}" y="{ly}" text-anchor="middle">'
                f'{e(ed["label"])}</text>'
            )

    detail = {}
    for n in nodes:
        x, y = _xy(n)
        st = _status_for(n.get("phase"), phases)
        kind = n.get("kind", "service")
        label = n["label"]
        # Wrap the label onto two lines if it is long.
        if len(label) > 20 and " " in label:
            cut = label.rfind(" ", 0, 22) or label.find(" ")
            lines = [label[:cut], label[cut + 1:]]
        else:
            lines = [label]
        ty = y + NODE_H / 2 + (5 if len(lines) == 1 else -3)

        out.append(f'<g class="nd {kind} {st}" data-id="{e(n["id"])}" tabindex="0">')
        out.append(
            f'<rect x="{x}" y="{y}" width="{NODE_W}" height="{NODE_H}" rx="6"/>'
        )
        for i, ln in enumerate(lines):
            out.append(
                f'<text class="ndl" x="{x + NODE_W / 2}" y="{ty + i * 14}" '
                f'text-anchor="middle">{e(ln)}</text>'
            )
        if st != "built" and n.get("phase") is not None:
            out.append(
                f'<text class="ndp" x="{x + NODE_W - 7}" y="{y + 13}" '
                f'text-anchor="end">P{n["phase"]}</text>'
            )
        out.append("</g>")

        detail[n["id"]] = {
            "label": label,
            "kind": kind,
            "phase": n.get("phase"),
            "status": st,
            "credentials": n.get("credentials", ""),
            "inputs": n.get("inputs", []),
            "outputs": n.get("outputs", []),
            "tables": n.get("tables", []),
            "note": n.get("note", ""),
            "edges_in": [
                {"from": by_id[x2["from"]]["label"], "label": x2.get("label", "")}
                for x2 in edges if x2["to"] == n["id"] and x2["from"] in by_id
            ],
            "edges_out": [
                {"to": by_id[x2["to"]]["label"], "label": x2.get("label", "")}
                for x2 in edges if x2["from"] == n["id"] and x2["to"] in by_id
            ],
        }

    out.append("</svg>")
    return "\n".join(out), detail


# ─────────────────────────────────────────────────────────────
# Rendering
# ─────────────────────────────────────────────────────────────

def e(s: str) -> str:
    return html.escape(str(s), quote=True)


def md_inline(s: str) -> str:
    """Escape, then honour the small subset of Markdown used in these docs."""
    s = e(s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![*\w])\*([^*]+)\*(?!\w)", r"<em>\1</em>", s)
    return s


CSS = """
:root{
  --paper:#F5F6F3; --surface:#FFFFFF; --raised:#FBFCFA;
  --ink:#10161A; --ink-2:#47555A; --ink-3:#7C8A8E;
  --rule:#DDE3E0; --rule-strong:#C3CCC8;
  --accent:#0E6E63; --accent-soft:#E2EFEC;
  --ok:#2F7A46; --warn:#9A6B12; --crit:#A63B2C;
  --crit-soft:#FBEBE8; --warn-soft:#FAF1DF;
  --track:#E7EBE8;
  --shadow:0 1px 2px rgba(16,22,26,.06);
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --paper:#0D1113; --surface:#151B1E; --raised:#1A2225;
    --ink:#E8EDEB; --ink-2:#9AAAA8; --ink-3:#6B7B7A;
    --rule:#263033; --rule-strong:#37454A;
    --accent:#4FBFAE; --accent-soft:#16302D;
    --ok:#5BB273; --warn:#D2A24C; --crit:#E0705C;
    --crit-soft:#2E1A17; --warn-soft:#2A2314;
    --track:#232C30;
    --shadow:0 1px 2px rgba(0,0,0,.3);
  }
}
:root[data-theme="dark"]{
  --paper:#0D1113; --surface:#151B1E; --raised:#1A2225;
  --ink:#E8EDEB; --ink-2:#9AAAA8; --ink-3:#6B7B7A;
  --rule:#263033; --rule-strong:#37454A;
  --accent:#4FBFAE; --accent-soft:#16302D;
  --ok:#5BB273; --warn:#D2A24C; --crit:#E0705C;
  --crit-soft:#2E1A17; --warn-soft:#2A2314;
  --track:#232C30;
  --shadow:0 1px 2px rgba(0,0,0,.3);
}

*{box-sizing:border-box}
body{
  background:var(--paper); color:var(--ink);
  font-family:Archivo,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  font-size:15px; line-height:1.55;
  -webkit-font-smoothing:antialiased;
}
.wrap{max-width:1040px; margin:0 auto; padding:32px 20px 72px}
code,.mono{font-family:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace}
code{font-size:.88em; background:var(--track); padding:.1em .35em; border-radius:3px}
a{color:var(--accent)}
h1,h2,h3{text-wrap:balance; margin:0}
.eyebrow{
  font-family:"IBM Plex Mono",monospace; font-size:11px; font-weight:500;
  letter-spacing:.14em; text-transform:uppercase; color:var(--ink-3);
}
section{margin-top:44px}
.sec-head{
  display:flex; align-items:baseline; gap:12px;
  padding-bottom:10px; border-bottom:1px solid var(--rule-strong); margin-bottom:18px;
}
.sec-head h2{font-size:15px; font-weight:600; letter-spacing:.01em}
.sec-head .count{
  font-family:"IBM Plex Mono",monospace; font-size:12px; color:var(--ink-3);
  margin-left:auto; font-variant-numeric:tabular-nums;
}

/* ── masthead ─────────────────────────────────────────── */
.mast{display:flex; flex-wrap:wrap; gap:24px; align-items:flex-end; justify-content:space-between}
.mast h1{font-size:30px; font-weight:700; letter-spacing:-.02em; line-height:1.1}
.mast .mal{color:var(--accent); font-weight:600}
.mast .sub{color:var(--ink-2); font-size:13.5px; margin-top:6px; max-width:56ch}

.readout{
  display:grid; grid-template-columns:repeat(auto-fit,minmax(112px,1fr));
  gap:1px; background:var(--rule); border:1px solid var(--rule);
  border-radius:6px; overflow:hidden; margin-top:26px;
}
.readout div{background:var(--surface); padding:12px 14px}
.readout dt{
  font-family:"IBM Plex Mono",monospace; font-size:10px; font-weight:500;
  letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3);
}
.readout dd{
  margin:5px 0 0; font-family:"IBM Plex Mono",monospace;
  font-size:20px; font-weight:500; font-variant-numeric:tabular-nums;
  letter-spacing:-.01em;
}
.readout dd small{font-size:12px; color:var(--ink-3); font-weight:400}

/* ── blockers ─────────────────────────────────────────── */
.blockers{
  border:1px solid var(--crit); border-left:4px solid var(--crit);
  background:var(--crit-soft); border-radius:5px; padding:16px 18px;
}
.blockers.clear{border-color:var(--ok); border-left-color:var(--ok); background:var(--accent-soft)}
.blockers h2{font-size:13px; font-weight:700; letter-spacing:.06em; text-transform:uppercase; color:var(--crit)}
.blockers.clear h2{color:var(--ok)}
.blockers ul{margin:12px 0 0; padding-left:20px; display:flex; flex-direction:column; gap:9px}
.blockers li{font-size:14px; line-height:1.5}

/* ── phase ladder ─────────────────────────────────────── */
.ladder{display:flex; flex-direction:column; gap:1px; background:var(--rule);
        border:1px solid var(--rule); border-radius:6px; overflow:hidden}
.ph{background:var(--surface); padding:13px 16px; display:grid;
    grid-template-columns:34px 1fr 132px 74px; gap:14px; align-items:center;
    list-style:none; cursor:pointer}
.ph::-webkit-details-marker{display:none}
.ph:hover{background:var(--raised)}
.ph.now{background:var(--raised); box-shadow:inset 3px 0 0 var(--accent)}
.ph.done .pname{color:var(--ink-2)}
.pnum{font-family:"IBM Plex Mono",monospace; font-size:17px; font-weight:500;
      color:var(--ink-3); font-variant-numeric:tabular-nums}
.ph.now .pnum{color:var(--accent); font-weight:600}
.pname{font-size:14.5px; font-weight:500}
.pmeta{font-size:12px; color:var(--ink-3); margin-top:2px}
.bar{height:5px; background:var(--track); border-radius:3px; overflow:hidden}
.bar span{display:block; height:100%; background:var(--accent); border-radius:3px}
.ph.done .bar span{background:var(--ok)}
.ptally{font-family:"IBM Plex Mono",monospace; font-size:12px; color:var(--ink-2);
        text-align:right; font-variant-numeric:tabular-nums}
.pill{display:inline-block; font-family:"IBM Plex Mono",monospace; font-size:10px;
      font-weight:500; letter-spacing:.08em; text-transform:uppercase;
      padding:2px 7px; border-radius:3px; border:1px solid currentColor}
.pill.local{color:var(--ink-3)}
.pill.paused{color:var(--warn)}
.pill.alwayson{color:var(--accent)}

.detail{background:var(--raised); padding:4px 16px 18px 64px; border-top:1px dashed var(--rule)}
.tasks{list-style:none; margin:14px 0 0; padding:0; display:flex; flex-direction:column; gap:7px}
.tasks li{display:flex; gap:10px; font-size:13.5px; align-items:baseline}
.tasks .box{font-family:"IBM Plex Mono",monospace; font-size:12px; color:var(--ink-3); flex:none}
.tasks li.ok .box{color:var(--ok)}
.tasks li.ok span:last-child{color:var(--ink-3); text-decoration:line-through}
.gate{margin-top:16px; padding:10px 13px; background:var(--surface);
      border:1px solid var(--rule); border-radius:4px; font-size:13px}
.gate b{font-family:"IBM Plex Mono",monospace; font-size:10px; font-weight:500;
        letter-spacing:.12em; text-transform:uppercase; color:var(--ink-3);
        display:block; margin-bottom:4px}

/* ── two-up ───────────────────────────────────────────── */
.two{display:grid; grid-template-columns:1fr 1fr; gap:40px}
.rows{display:flex; flex-direction:column}
.row{display:flex; gap:12px; align-items:baseline; padding:9px 0; border-bottom:1px solid var(--rule)}
.row:last-child{border-bottom:0}
.row .k{font-family:"IBM Plex Mono",monospace; font-size:12px; color:var(--ink-3); flex:none; min-width:56px}
.row .v{flex:1; font-size:13.5px}
.row .t{font-family:"IBM Plex Mono",monospace; font-size:11.5px; color:var(--ink-3);
        margin-left:auto; flex:none; font-variant-numeric:tabular-nums}
.tag{font-family:"IBM Plex Mono",monospace; font-size:10px; letter-spacing:.07em;
     text-transform:uppercase; padding:2px 6px; border-radius:3px; flex:none}
.tag.open{background:var(--warn-soft); color:var(--warn)}
.tag.settled{background:var(--accent-soft); color:var(--accent)}

/* ── cost ─────────────────────────────────────────────── */
.gauge{border:1px solid var(--rule); border-radius:6px; background:var(--surface); padding:18px}
.gauge .top{display:flex; align-items:baseline; gap:10px}
.gauge .amt{font-family:"IBM Plex Mono",monospace; font-size:30px; font-weight:500;
            font-variant-numeric:tabular-nums; letter-spacing:-.02em}
.gauge .of{color:var(--ink-3); font-size:13px}
.track{height:9px; background:var(--track); border-radius:5px; margin:14px 0 6px; position:relative; overflow:hidden}
.track span{display:block; height:100%; background:var(--ok); border-radius:5px}
.ticks{display:flex; justify-content:space-between; font-family:"IBM Plex Mono",monospace;
       font-size:10.5px; color:var(--ink-3); font-variant-numeric:tabular-nums}
.costnote{margin-top:14px; font-size:13px; color:var(--ink-2); line-height:1.55}

/* ── links ────────────────────────────────────────────── */
.links{display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); gap:1px;
       background:var(--rule); border:1px solid var(--rule); border-radius:6px; overflow:hidden}
.links a,.links div.dead{background:var(--surface); padding:13px 15px; text-decoration:none; display:block}
.links a:hover{background:var(--accent-soft)}
.links .lab{font-size:13.5px; font-weight:500; color:var(--ink)}
.links a .lab{color:var(--accent)}
.links .note{font-size:12px; color:var(--ink-3); margin-top:3px}
.links .dead .lab{color:var(--ink-3)}
.links .dead .lab::after{content:" — not yet created"; font-family:"IBM Plex Mono",monospace;
                         font-size:10px; letter-spacing:.06em; text-transform:uppercase; color:var(--warn)}

/* ── architecture entry cards ─────────────────────────── */
.archcards{display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:12px}
.archcard{display:block; text-decoration:none; background:var(--surface); border:1px solid var(--rule-strong);
  border-top:3px solid var(--accent); border-radius:6px; padding:16px 17px; transition:border-color .1s}
.archcard:hover{border-color:var(--accent); background:var(--accent-soft)}
.archcard .at{font-size:15px; font-weight:600; color:var(--ink)}
.archcard .ad{font-size:12.5px; color:var(--ink-2); margin-top:5px; line-height:1.5}
.archcard .as{font-family:"IBM Plex Mono",monospace; font-size:11px; color:var(--ink-3);
  margin-top:11px; padding-top:10px; border-top:1px solid var(--rule)}

/* ── learn: link on a phase row ────────────────────────── */
.learn-link{font-family:"IBM Plex Mono",monospace; font-size:10px; font-weight:500;
  letter-spacing:.09em; text-transform:uppercase; text-decoration:none;
  color:var(--accent); border:1px solid var(--accent); border-radius:3px;
  padding:2px 7px; white-space:nowrap}
.learn-link:hover{background:var(--accent); color:var(--surface)}
.pmeta .learn-link{margin-left:6px}

/* ── learn: the concept page itself ───────────────────── */
.view[hidden]{display:none}
.lnav{display:flex; align-items:center; gap:14px; flex-wrap:wrap;
      padding-bottom:14px; border-bottom:1px solid var(--rule-strong); margin-bottom:8px}
.lnav a{font-family:"IBM Plex Mono",monospace; font-size:11.5px; letter-spacing:.06em;
        text-transform:uppercase; text-decoration:none}
.lnav a:hover{text-decoration:underline}
.lnav .spacer{margin-left:auto}
.lnav .off{color:var(--ink-3); pointer-events:none}
.wf{font-family:"IBM Plex Mono",monospace; font-size:10px; letter-spacing:.08em;
    text-transform:uppercase; padding:2px 7px; border-radius:3px}
.wf.experience{background:var(--accent-soft); color:var(--accent)}
.wf.theory{background:var(--warn-soft); color:var(--warn)}

.prose{max-width:68ch}
.prose h1{font-size:27px; font-weight:700; letter-spacing:-.02em; margin:22px 0 0}
.prose h2{font-size:19px; font-weight:600; letter-spacing:-.01em; margin:42px 0 0;
          padding-bottom:7px; border-bottom:1px solid var(--rule)}
.prose h3{font-size:15.5px; font-weight:600; margin:30px 0 0; color:var(--accent)}
.prose h4{font-size:14px; font-weight:600; margin:22px 0 0}
.prose p{margin:13px 0 0}
.prose ul,.prose ol{margin:13px 0 0; padding-left:24px; display:flex;
                    flex-direction:column; gap:7px}
.prose li{padding-left:3px}
.prose blockquote{margin:16px 0 0; padding:11px 15px; background:var(--raised);
  border-left:3px solid var(--accent); border-radius:0 4px 4px 0;
  font-size:13px; color:var(--ink-2)}
.prose blockquote code{background:transparent; padding:0}
.prose pre{margin:16px 0 0; padding:13px 15px; background:var(--raised);
  border:1px solid var(--rule); border-radius:5px; overflow-x:auto; font-size:12.5px;
  line-height:1.5}
.prose pre code{background:transparent; padding:0; font-size:inherit}
.prose hr{margin:38px 0 0; border:0; border-top:1px solid var(--rule)}
.prose .tw{margin:16px 0 0; overflow-x:auto; border:1px solid var(--rule); border-radius:5px}
.prose table{border-collapse:collapse; width:100%; font-size:13px}
.prose th{text-align:left; font-family:"IBM Plex Mono",monospace; font-size:10.5px;
  font-weight:500; letter-spacing:.09em; text-transform:uppercase; color:var(--ink-3);
  padding:9px 13px; background:var(--raised); border-bottom:1px solid var(--rule)}
.prose td{padding:9px 13px; border-bottom:1px solid var(--rule); vertical-align:top}
.prose tbody tr:last-child td{border-bottom:0}
.prose a{text-decoration:underline; text-underline-offset:2px}

.index{display:grid; grid-template-columns:repeat(auto-fit,minmax(232px,1fr)); gap:1px;
       background:var(--rule); border:1px solid var(--rule); border-radius:6px; overflow:hidden}
.index a{background:var(--surface); padding:13px 15px; text-decoration:none; display:block}
.index a:hover{background:var(--accent-soft)}
.index .n{font-family:"IBM Plex Mono",monospace; font-size:11px; color:var(--ink-3)}
.index .t{font-size:13.5px; font-weight:500; color:var(--ink); margin-top:2px}
.index .m{font-size:11.5px; color:var(--ink-3); margin-top:4px}

/* ── architecture diagrams ────────────────────────────── */
.dwrap{overflow-x:auto; border:1px solid var(--rule); border-radius:6px;
       background:var(--surface); padding:6px 2px}
.diagram{display:block; max-width:none}

.nd rect{fill:var(--surface); stroke:var(--rule-strong); stroke-width:1.5}
.nd .ndl{font-family:Archivo,sans-serif; font-size:11.5px; font-weight:500;
         fill:var(--ink); pointer-events:none}
.nd .ndp{font-family:"IBM Plex Mono",monospace; font-size:8.5px; font-weight:500;
         fill:var(--ink-3); letter-spacing:.06em; pointer-events:none}
.nd{cursor:pointer}
.nd:hover rect{stroke:var(--accent); stroke-width:2}
.nd:focus{outline:none}
.nd:focus rect{stroke:var(--accent); stroke-width:2.5}
.nd.sel rect{stroke:var(--accent); stroke-width:2.5; fill:var(--accent-soft)}

.nd.planned rect{stroke-dasharray:5 3; stroke:var(--rule-strong); fill:var(--paper)}
.nd.planned .ndl{fill:var(--ink-3)}
.nd.active rect{stroke:var(--accent); stroke-width:2}
.nd.built.store rect,.nd.active.store rect{fill:var(--accent-soft)}
.nd.built.decision rect,.nd.active.decision rect{fill:var(--warn-soft); stroke:var(--warn)}
.nd.planned.decision rect{stroke:var(--warn)}
.nd.decision .ndl{font-style:italic}
.nd.built.terminal rect,.nd.active.terminal rect{fill:var(--crit-soft); stroke:var(--crit)}
.nd.planned.terminal rect{stroke:var(--crit)}
.nd.built.source rect,.nd.active.source rect{fill:var(--raised)}
.nd.external rect{stroke-dasharray:2 2}
.nd.built.platform rect,.nd.active.platform rect{fill:var(--raised)}

.ed{fill:none; stroke:var(--rule-strong); stroke-width:1.4; color:var(--rule-strong)}
.ed.planned{stroke:var(--rule); color:var(--rule); stroke-dasharray:4 3}
.ed.built{stroke:var(--accent); color:var(--accent)}
.ed.feedback{stroke-dasharray:3 3}
.ed.platform{stroke-width:1}
.edl{font-family:"IBM Plex Mono",monospace; font-size:8.5px; fill:var(--ink-3);
     letter-spacing:.02em}
.edl.planned{fill:var(--ink-3); opacity:.65}

.dlegend{display:flex; flex-wrap:wrap; gap:16px; margin-top:12px;
         font-family:"IBM Plex Mono",monospace; font-size:10.5px; color:var(--ink-3)}
.dlegend b{font-weight:500; color:var(--ink-2)}

.ndetail{margin-top:18px; border:1px solid var(--rule); border-radius:6px;
         background:var(--surface); padding:16px 18px; min-height:96px}
.ndetail .hint{color:var(--ink-3); font-size:13px}
.ndetail h3{font-size:16px; font-weight:600; margin:0}
.ndetail .top{display:flex; align-items:baseline; gap:10px; flex-wrap:wrap;
              padding-bottom:11px; border-bottom:1px solid var(--rule)}
.ndetail dl{display:grid; grid-template-columns:104px 1fr; gap:9px 14px; margin:13px 0 0}
.ndetail dt{font-family:"IBM Plex Mono",monospace; font-size:10px; letter-spacing:.1em;
            text-transform:uppercase; color:var(--ink-3); padding-top:2px}
.ndetail dd{margin:0; font-size:13.5px}
.ndetail dd ul{margin:0; padding-left:16px; display:flex; flex-direction:column; gap:4px}
.ndetail .note{margin:15px 0 0; padding:11px 14px; background:var(--raised);
               border-left:3px solid var(--accent); border-radius:0 4px 4px 0;
               font-size:13px; color:var(--ink-2); line-height:1.55}
.ndetail .warn{color:var(--crit); font-weight:600}
.st{font-family:"IBM Plex Mono",monospace; font-size:10px; letter-spacing:.08em;
    text-transform:uppercase; padding:2px 7px; border-radius:3px}
.st.built{background:var(--accent-soft); color:var(--accent)}
.st.active{background:var(--warn-soft); color:var(--warn)}
.st.planned{background:var(--track); color:var(--ink-3)}

.tabs{display:flex; gap:8px; margin-bottom:16px; flex-wrap:wrap}
.tabs a{font-family:"IBM Plex Mono",monospace; font-size:11.5px; letter-spacing:.06em;
        text-transform:uppercase; text-decoration:none; padding:6px 13px;
        border:1px solid var(--rule-strong); border-radius:4px; color:var(--ink-2)}
.tabs a:hover{border-color:var(--accent); color:var(--accent)}
.tabs a.on{background:var(--accent); border-color:var(--accent); color:var(--surface)}

footer{margin-top:56px; padding-top:16px; border-top:1px solid var(--rule);
       font-size:12px; color:var(--ink-3); display:flex; flex-wrap:wrap; gap:14px}

a:focus-visible,summary:focus-visible{outline:2px solid var(--accent); outline-offset:2px}
@media (max-width:720px){
  .wrap{padding:22px 15px 56px}
  .mast h1{font-size:25px}
  .ph{grid-template-columns:26px 1fr; row-gap:9px}
  .ph .barwrap{grid-column:1/-1}
  .ptally{text-align:left; grid-column:1/-1}
  .detail{padding-left:22px}
  .dwrap{margin-left:-15px; margin-right:-15px; border-radius:0; border-left:0; border-right:0}
  .ndetail dl{grid-template-columns:1fr; gap:3px 0}
  .ndetail dt{padding-top:9px}
  .two{grid-template-columns:1fr; gap:34px}
  .row{flex-wrap:wrap}
}
@media (prefers-reduced-motion:reduce){*{animation:none!important; transition:none!important}}
"""


def render(cfg: dict, phases: list[Phase], adrs: list[dict], labs: list[dict],
           sessions: list[dict], threads: list[str], commits: list[dict],
           learn: list[Learn], arch: dict, releases: list[dict]) -> str:
    proj = cfg["project"]
    cost = cfg["cost"]
    posture = cfg.get("posture", {})

    today = date.today()
    started = date.fromisoformat(proj["started"])
    target = date.fromisoformat(proj["target_v1"])
    elapsed = (today - started).days
    remaining = (target - today).days

    total_tasks = sum(p.total for p in phases)
    done_tasks = sum(p.done for p in phases)
    overall = round(100 * done_tasks / total_tasks) if total_tasks else 0

    current = next((p for p in phases if p.marker == "~"),
                   next((p for p in phases if p.marker == " "), phases[-1]))

    open_adrs = [a for a in adrs if a["open"]]
    # An open thread that already names the ADR covers it; don't say it twice.
    blockers = list(threads) + [
        f'{a["id"]} <em>{e(a["title"])}</em> is still Proposed — the decision is not settled.'
        for a in open_adrs
        if not any(a["id"].lower() in t.lower() for t in threads)
    ]

    mtd = float(cost.get("mtd_usd", 0))
    ceiling = float(cost["ceiling_usd"])
    pct_cost = min(100, round(100 * mtd / ceiling)) if ceiling else 0

    by_num = {l.num: l for l in learn if l.num is not None}

    # ── masthead ──
    parts = [f"""<div class="wrap">
<div class="view" id="view-board">
<header class="mast">
  <div>
    <div class="eyebrow">Progress · phase {current.num} of {len(phases)}</div>
    <h1>{e(proj["name"])} <span class="mal">{e(proj["tagline"].split("—")[0].strip())}</span></h1>
    <p class="sub">Autonomous ops agent with human-in-the-loop approval. Watches a Kubernetes
    cluster and an AWS bill, diagnoses with a self-hosted Gemma&nbsp;3&nbsp;1B, and acts only
    after a tap on a phone.</p>
  </div>
</header>

<dl class="readout">
  <div><dt>Complete</dt><dd>{overall}<small>%</small></dd></div>
  <div><dt>Tasks</dt><dd>{done_tasks}<small>/{total_tasks}</small></dd></div>
  <div><dt>Current</dt><dd>{current.num}<small>&nbsp;{e(current.state)}</small></dd></div>
  <div><dt>Day</dt><dd>{elapsed}<small>&nbsp;since start</small></dd></div>
  <div><dt>To v1</dt><dd>{remaining}<small>&nbsp;days</small></dd></div>
  <div><dt>Spend MTD</dt><dd>${mtd:.2f}</dd></div>
</dl>"""]

    # ── blockers ──
    if blockers:
        items = "\n".join(f"    <li>{md_inline(b) if '<em>' not in b else b}</li>" for b in blockers)
        parts.append(f"""
<section>
  <div class="blockers">
    <h2>Blocked on — {len(blockers)}</h2>
    <ul>
{items}
    </ul>
  </div>
</section>""")
    else:
        parts.append("""
<section><div class="blockers clear"><h2>Nothing blocked</h2></div></section>""")

    # ── architecture entry cards ──
    arch_cards = [
        ("system", "System topology", "What exists and what talks to what — every credential and data flow, labelled."),
        ("journey", "Incident journey", "One incident, every branch: policy never/ask/auto, escalation, human decision, outcome."),
        ("delivery", "Delivery pipeline", "PR → CI → staging → gate → prod → verify, with the rollback path."),
    ]
    cards_html = []
    for view, title, desc in arch_cards:
        ns = arch.get(view, {}).get("node", [])
        built = sum(1 for n in ns if _status_for(n.get("phase"), phases) == "built")
        cards_html.append(f"""  <a class="archcard" href="#{view}">
    <div class="at">{e(title)}</div>
    <div class="ad">{e(desc)}</div>
    <div class="as">{len(ns)} nodes · {built} built</div>
  </a>""")
    parts.append(f"""
<section>
  <div class="sec-head"><div class="eyebrow">What the thing actually is</div><h2>Architecture</h2></div>
  <div class="archcards">
{chr(10).join(cards_html)}
  </div>
</section>""")

    # ── phase ladder ──
    rows = []
    for p in phases:
        pst = posture.get(str(p.num), {})
        cls = "ph"
        if p is current:
            cls += " now"
        if p.marker == "x":
            cls += " done"
        pill = pst.get("state", "")
        pill_cls = pill.replace("-", "")
        lrn = by_num.get(p.num)
        lnk = f'<a class="learn-link" href="#phase-{p.num}">Learn</a>' if lrn else ""
        tasks = "\n".join(
            f'      <li class="{"ok" if ok else ""}"><span class="box">{"[x]" if ok else "[ ]"}</span>'
            f"<span>{md_inline(t)}</span></li>"
            for ok, t in p.tasks
        )
        open_attr = " open" if p is current else ""
        rows.append(f"""  <details{open_attr}>
  <summary class="{cls}">
    <div class="pnum">{p.num}</div>
    <div>
      <div class="pname">{e(p.title)}</div>
      <div class="pmeta">weeks {e(p.weeks)} · <span class="pill {pill_cls}">{e(pill)}</span> {e(pst.get("cost",""))}{lnk}</div>
    </div>
    <div class="barwrap"><div class="bar"><span style="width:{p.pct}%"></span></div></div>
    <div class="ptally">{p.done}/{p.total}</div>
  </summary>
  <div class="detail">
    <ul class="tasks">
{tasks}
    </ul>
    <div class="gate"><b>Exit gate</b>{md_inline(p.exit_gate)}</div>
  </div>
  </details>""")

    parts.append(f"""
<section>
  <div class="sec-head"><div class="eyebrow">Sequential · gated · click a phase to expand</div><h2>Phases</h2>
    <div class="count">{done_tasks}/{total_tasks} tasks</div></div>
  <div class="ladder">
{chr(10).join(rows)}
  </div>
</section>""")

    # ── learning index ──
    if learn:
        from_exp = sum(1 for l in learn if l.written_from == "experience")
        cards = "\n".join(
            f'  <a href="#{l.key}"><div class="n">{l.eyebrow}</div>'
            f'<div class="t">{e(l.title)}</div>'
            f'<div class="m">{l.terms} terms · written from {e(l.written_from)}</div></a>'
            for l in learn
        )
        parts.append(f"""
<section>
  <div class="sec-head"><div class="eyebrow">Concepts, not steps</div><h2>Learn</h2>
    <div class="count"><a href="#system">System diagram</a> · <a href="#journey">Journey</a>
    · {from_exp}/{len(learn)} from experience</div></div>
  <div class="index">
{cards}
  </div>
</section>""")

    # ── cost ──
    prov = "Nothing provisioned yet." if not cost.get("provisioned") else "Live."
    parts.append(f"""
<section>
  <div class="sec-head"><div class="eyebrow">Guardrails before compute</div><h2>Cost</h2>
    <div class="count">ceiling ${ceiling:.0f}/mo</div></div>
  <div class="gauge">
    <div class="top"><span class="amt">${mtd:.2f}</span><span class="of">month to date, of ${ceiling:.0f} ceiling</span></div>
    <div class="track"><span style="width:{pct_cost}%"></span></div>
    <div class="ticks"><span>$0</span><span>$18 alert</span><span>$22 alert</span><span>$24 hard stop</span></div>
    <p class="costnote">{prov} Projected total for the whole project,
    {started:%b&nbsp;%Y} → {target:%b&nbsp;%Y}: <strong>~${cost["projected_total"]}</strong>;
    budget <strong>${cost["budget_with_buffer"]}</strong> to absorb one mistake. Phase
    {current.num} run posture is <strong>{e(posture.get(str(current.num),{}).get("state","—"))}</strong>
    at {e(posture.get(str(current.num),{}).get("cost","—"))}.</p>
  </div>
</section>""")

    # ── decisions + labs ──
    adr_rows = "\n".join(
        f"""    <div class="row"><span class="k">{e(a["id"])}</span>
      <span class="v">{e(a["title"])}</span>
      <span class="tag {"open" if a["open"] else "settled"}">{e(a["status"].split()[0])}</span></div>"""
        for a in adrs
    ) or '    <div class="row"><span class="v">None yet.</span></div>'

    lab_rows = "\n".join(
        f"""    <div class="row"><span class="k">{e(l["id"])}</span>
      <span class="v">{e(l["title"])}</span>
      <span class="t">{l["done"]}/{l["total"]}</span></div>"""
        for l in labs
    ) or '    <div class="row"><span class="v">None yet.</span></div>'

    parts.append(f"""
<section class="two">
  <div>
    <div class="sec-head"><h2>Decisions</h2>
      <div class="count">{len(open_adrs)} open</div></div>
    <div class="rows">
{adr_rows}
    </div>
  </div>
  <div>
    <div class="sec-head"><h2>Labs</h2>
      <div class="count">{len(labs)} written</div></div>
    <div class="rows">
{lab_rows}
    </div>
  </div>
</section>""")

    # ── activity ──
    commit_rows = "\n".join(
        f"""    <div class="row"><span class="k">{e(c["date"])}</span>
      <span class="v">{e(c["subject"])}</span>
      <span class="t">{e(c["hash"])}</span></div>"""
        for c in commits
    ) or '    <div class="row"><span class="v">No commits yet.</span></div>'

    session_rows = "\n".join(
        f"""    <div class="row"><span class="k">{e(s["date"])}</span>
      <span class="v">{e(s["phase"])}</span></div>"""
        for s in sessions
    ) or '    <div class="row"><span class="v">No sessions logged.</span></div>'

    last = sessions[0]["date"] if sessions else "—"
    gap = (today - date.fromisoformat(last)).days if sessions else 0

    parts.append(f"""
<section class="two">
  <div>
    <div class="sec-head"><h2>Commits</h2><div class="count">{len(commits)} recent</div></div>
    <div class="rows">
{commit_rows}
    </div>
  </div>
  <div>
    <div class="sec-head"><h2>Sessions</h2>
      <div class="count">{"today" if gap == 0 else f"{gap}d since last"}</div></div>
    <div class="rows">
{session_rows}
    </div>
  </div>
</section>""")

    # ── links ──
    link_cards = []
    for l in cfg.get("links", []):
        if l.get("url"):
            link_cards.append(
                f'  <a href="{e(l["url"])}"><div class="lab">{e(l["label"])}</div>'
                f'<div class="note">{e(l.get("note",""))}</div></a>'
            )
        else:
            link_cards.append(
                f'  <div class="dead"><div class="lab">{e(l["label"])}</div>'
                f'<div class="note">{e(l.get("note",""))}</div></div>'
            )

    # ── environments and releases ──
    envs = cfg.get("environments", [])
    if envs:
        latest = {}
        for r in releases:
            latest.setdefault(r["env"], r)
        rows = []
        for en in envs:
            r = latest.get(en["name"])
            gate = "" if en.get("promotion", True) else                 '<span class="tag open">not a gate</span>'
            ver = (f'<span class="mono">{e(r["version"])}</span> '
                   f'<span style="color:var(--ink-3)" class="mono">{e(r["digest"])}</span>'
                   if r else '<span style="color:var(--ink-3)">—</span>')
            rows.append(f"""    <div class="row"><span class="k">{e(en["name"])}</span>
      <span class="v">{e(en["where"])}<div class="pmeta">{e(en["lifetime"])} · {e(en.get("cost",""))}</div></span>
      {gate}<span class="t">{ver}</span></div>""")

        if releases:
            rel_rows = chr(10).join(
                f"""    <div class="row"><span class="k mono">{e(r["version"])}</span>
      <span class="v">{e(r["date"])} · approved by {e(r["approver"] or "—")}</span>
      {'<span class="tag open">rolled back</span>' if r["rolled_back"] else ''}
      <span class="t">{e(r["env"])}</span></div>"""
                for r in releases[:8]
            )
        else:
            rel_rows = ('    <div class="row"><span class="v">No releases yet. '
                        'The first arrives with the pipeline in Phase 4.</span></div>')

        m = dora(releases, started, today)
        if m:
            met = f"""
  <div class="readout" style="margin-top:18px">
    <div><dt>Deploy freq</dt><dd>{e(m["frequency"])}</dd></div>
    <div><dt>Lead time</dt><dd>{e(m["lead_time"])}</dd></div>
    <div><dt>Change failure</dt><dd>{e(m["change_failure"])}</dd></div>
    <div><dt>Time to restore</dt><dd>{e(m["restore"])}</dd></div>
  </div>"""
        else:
            met = (chr(10) + '  <p class="costnote" style="margin-top:14px">DORA metrics — deployment '
                   'frequency, lead time, change failure rate, time to restore — are measured '
                   'from these records once releases begin. Speed and stability, two pairs; '
                   'reporting only one is how teams justify shipping recklessly, or never.</p>')

        parts.append(f"""
<section class="two">
  <div>
    <div class="sec-head"><div class="eyebrow">local → staging → prod</div><h2>Environments</h2>
      <div class="count"><a href="#delivery">Delivery flow</a></div></div>
    <div class="rows">
{chr(10).join(rows)}
    </div>
  </div>
  <div>
    <div class="sec-head"><h2>Releases</h2>
      <div class="count">{len(releases)} shipped</div></div>
    <div class="rows">
{rel_rows}
    </div>
  </div>
</section>{met}""")

    parts.append(f"""
<section>
  <div class="sec-head"><h2>Links &amp; notes</h2></div>
  <div class="links">
{chr(10).join(link_cards)}
  </div>
</section>
</div>""")

    # ── concept pages ──
    for idx, l in enumerate(learn):
        prev = learn[idx - 1] if idx > 0 else None
        nxt = learn[idx + 1] if idx + 1 < len(learn) else None
        pv = (f'<a href="#{prev.key}">← {prev.eyebrow}</a>'
              if prev else '<a class="off">← start</a>')
        nx = (f'<a href="#{nxt.key}">{nxt.eyebrow} →</a>'
              if nxt else '<a class="off">End →</a>')
        parts.append(f"""
<div class="view" id="view-{l.key}" hidden>
  <nav class="lnav">
    <a href="#board">↑ Board</a>
    <span class="wf {e(l.written_from)}">written from {e(l.written_from)}</span>
    <span class="spacer"></span>
    {pv}
    {nx}
  </nav>
  <article class="prose">
{l.body}
  </article>
  <nav class="lnav" style="border:0;border-top:1px solid var(--rule-strong);
       padding:14px 0 0;margin:40px 0 0">
    <a href="#board">↑ Board</a><span class="spacer"></span>{pv}{nx}
  </nav>
</div>""")

    # ── architecture views ──
    details: dict = {}
    VIEWS = (
        ("system", "System",
         "What exists and what talks to what. Every edge is labelled with what flows "
         "and under which credential — which is where the read-only/write split stops "
         "being a claim and becomes visible."),
        ("journey", "Journey",
         "One incident from fault to measured outcome, including the paths people leave "
         "out: policy refusal, human denial, escalation, execution failure."),
        ("delivery", "Delivery",
         "How a change reaches production: local → staging → prod, with a gate that "
         "can refuse. Deliberately the same shape as the product — validate, gate, "
         "human-approve, execute, verify."),
    )
    for view, title, blurb in VIEWS:
        block = arch.get(view, {})
        nodes, edges = block.get("node", []), block.get("edge", [])
        if not nodes:
            continue
        svg, det = render_diagram(view, nodes, edges, phases)
        details[view] = det
        built = sum(1 for n in nodes if _status_for(n.get("phase"), phases) == "built")
        active = sum(1 for n in nodes if _status_for(n.get("phase"), phases) == "active")
        tally = f"{built} built" + (f" · {active} in progress" if active else "")
        tabs = chr(10).join(
            f'    <a class="{"on" if v == view else ""}" href="#{v}">{t}</a>'
            for v, t, _ in VIEWS
        )
        parts.append(f"""
<div class="view" id="view-{view}" hidden>
  <nav class="lnav">
    <a href="#board">↑ Board</a>
    <span class="spacer"></span>
    <span class="wf {'experience' if built else 'theory'}">{tally} of {len(nodes)}</span>
  </nav>
  <div class="tabs">
{tabs}
  </div>
  <p class="sub" style="margin:0 0 18px;max-width:64ch;color:var(--ink-2);font-size:13.5px">{blurb}</p>
  <div class="dwrap">
{svg}
  </div>
  <div class="dlegend">
    <span><b>solid</b> built</span>
    <span><b>dashed + P<i>n</i></b> arrives in phase <i>n</i></span>
    <span><b>amber</b> decision</span>
    <span><b>red</b> terminal path</span>
    <span>tap any box for its inputs, outputs and credentials</span>
  </div>
  <div class="ndetail" id="det-{view}">
    <p class="hint">Select a component above to see every input, output and credential it holds.</p>
  </div>
</div>""")

    # "</" is split so the JSON can never terminate the <script> element early.
    detail_json = json.dumps(details).replace("</", "<\/")

    parts.append(f"""
<footer>
  <span>Generated {today:%Y-%m-%d} from the repository.</span>
  <span>Status lives in <code>ROADMAP.md</code> — this page only reflects it.</span>
  <span>Regenerate with <code>make dashboard</code>.</span>
</footer>
</div>
<script>
(function () {{
  var views = document.querySelectorAll('.view');
  function show() {{
    var id = (location.hash || '#board').slice(1);
    var target = document.getElementById('view-' + id) || document.getElementById('view-board');
    views.forEach(function (v) {{ v.hidden = (v !== target); }});
    window.scrollTo(0, 0);
  }}
  window.addEventListener('hashchange', show);
  show();

  var DETAIL = {detail_json};

  function esc(s) {{
    return String(s).replace(/[&<>"]/g, function (c) {{
      return {{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}}[c];
    }});
  }}

  function list(items) {{
    if (!items || !items.length) return '<dd>—</dd>';
    return '<dd><ul>' + items.map(function (i) {{
      return '<li>' + esc(i) + '</li>';
    }}).join('') + '</ul></dd>';
  }}

  function flows(items, key) {{
    if (!items || !items.length) return '<dd>—</dd>';
    return '<dd><ul>' + items.map(function (i) {{
      return '<li>' + esc(i[key]) + (i.label ? ' <span style="color:var(--ink-3)">— '
        + esc(i.label) + '</span>' : '') + '</li>';
    }}).join('') + '</ul></dd>';
  }}

  Object.keys(DETAIL).forEach(function (view) {{
    var panel = document.getElementById('det-' + view);
    var svg = document.querySelector('#view-' + view + ' .diagram');
    if (!panel || !svg) return;

    function select(g) {{
      var d = DETAIL[view][g.getAttribute('data-id')];
      if (!d) return;
      svg.querySelectorAll('.nd').forEach(function (n) {{ n.classList.remove('sel'); }});
      g.classList.add('sel');

      var cred = esc(d.credentials || '—');
      if (/READ-ONLY|SCOPED WRITE/.test(d.credentials || '')) {{
        cred = '<span class="warn">' + cred + '</span>';
      }}
      var ph = (d.phase === null || d.phase === undefined) ? '' :
        '<a href="#phase-' + d.phase + '" style="font-size:12px">Phase ' + d.phase + ' concepts →</a>';

      panel.innerHTML =
        '<div class="top"><h3>' + esc(d.label) + '</h3>' +
        '<span class="st ' + d.status + '">' + d.status + '</span>' +
        '<span style="margin-left:auto">' + ph + '</span></div>' +
        '<dl>' +
        '<dt>Credentials</dt><dd>' + cred + '</dd>' +
        '<dt>Receives</dt>' + flows(d.edges_in, 'from') +
        '<dt>Sends to</dt>' + flows(d.edges_out, 'to') +
        (d.inputs.length ? '<dt>Inputs</dt>' + list(d.inputs) : '') +
        (d.outputs.length ? '<dt>Outputs</dt>' + list(d.outputs) : '') +
        (d.tables.length ? '<dt>Tables</dt>' + list(d.tables) : '') +
        '</dl>' +
        (d.note ? '<p class="note">' + esc(d.note) + '</p>' : '');
    }}

    svg.querySelectorAll('.nd').forEach(function (g) {{
      g.addEventListener('click', function () {{ select(g); }});
      g.addEventListener('keydown', function (ev) {{
        if (ev.key === 'Enter' || ev.key === ' ') {{ ev.preventDefault(); select(g); }}
      }});
    }});
  }});
}})();
</script>""")

    return f"""<title>Kaval Watchtower</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>{CSS}</style>
{"".join(parts)}
"""


def main() -> None:
    cfg = tomllib.loads((ROOT / "dashboard.toml").read_text(encoding="utf-8"))
    phases = read_roadmap(ROOT / "ROADMAP.md")
    adrs = read_adrs(ROOT / "docs" / "adr")
    labs = read_labs(ROOT / "docs" / "labs")
    sessions, threads = read_journal(ROOT / "docs" / "journal")
    commits = git_log()
    learn = read_learn(ROOT / "docs" / "learn")
    af = ROOT / "architecture.toml"
    arch = tomllib.loads(af.read_text(encoding="utf-8")) if af.exists() else {}
    releases = read_releases(ROOT / "docs" / "releases")

    OUT.write_text(
        render(cfg, phases, adrs, labs, sessions, threads, commits, learn, arch, releases),
        encoding="utf-8",
    )

    done = sum(p.done for p in phases)
    total = sum(p.total for p in phases)
    exp = sum(1 for l in learn if l.written_from == "experience")
    print(f"  {OUT.relative_to(ROOT)}")
    print(f"  {len(phases)} phases · {done}/{total} tasks · {len(adrs)} ADRs "
          f"({sum(a['open'] for a in adrs)} open) · {len(labs)} labs · {len(threads)} open threads")
    print(f"  {len(learn)} concept pages ({exp} from experience) · "
          f"{sum(l.terms for l in learn)} glossary terms")
    print(f"  {len(releases)} releases · {len(cfg.get('environments', []))} environments")
    for v in ("system", "journey", "delivery"):
        ns = arch.get(v, {}).get("node", [])
        if ns:
            b = sum(1 for n in ns if _status_for(n.get("phase"), phases) == "built")
            print(f"  {v}: {len(ns)} nodes ({b} built) · "
                  f"{len(arch[v].get('edge', []))} edges")


if __name__ == "__main__":
    main()
